name: My App Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -r .next public package.json next.config.mjs deploy/
          cd deploy && zip -r ../deploy.zip .

      - name: Copy build to remote Windows server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.WIN_SERVER_HOST }}
          username: ${{ secrets.WIN_SERVER_USER }}
          key: ${{ secrets.WIN_SERVER_SSH_KEY }}
          port: 22
          source: deploy.zip
          target: D:/GitHubActions/

      - name: Run commands on remote Windows server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.WIN_SERVER_HOST }}
          username: ${{ secrets.WIN_SERVER_USER }}
          key: ${{ secrets.WIN_SERVER_SSH_KEY }}
          port: 22
          script: |
            powershell -Command "
              Expand-Archive -Path 'D:\GitHubActions\deploy.zip' -DestinationPath 'D:\GitHubActions\app' -Force;
              cd 'D:\GitHubActions\app';
              npm install --omit=dev;
              npm run reload
            "
